version: "3"

services:
  server:
    build: ./server
    container_name: crud_server_container
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=mongodb://db:27017/crud
      - PORT=8080

  client:
    build: ./client
    container_name: crud_client_container
    restart: always
    ports:
      - 3000:3000

  db:
    image: mongo:latest
    container_name: crud_db_container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

volumes:
  db:
